ChossonKallahAdmin/Areas/Xpanel/Controllers/BusinessGalleryController.cs
using ChossonKallah.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace ChossonKallah.Controllers
{
    public class BusinessGalleryController : Controller
    {
        DataTable dt = new DataTable();



        public ActionResult Create()
        {
            using (BusinessGalleryCtl db = new BusinessGalleryCtl())
            {
                Session["CreatePreviousURL"] = Convert.ToString(ControllerContext.HttpContext.Request.UrlReferrer);
                return View();
            }

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BusinessGalleryClass Obj_BusinessGallery, string command)
        {

            using (BusinessGalleryCtl db = new BusinessGalleryCtl())
            {
                if (ModelState.IsValid)
                {
                    db.insert(Obj_BusinessGallery);
                    if (command.ToLower().Trim() == "save")
                    {
                        string sesionval = Convert.ToString(Session["CreatePreviousURL"]);
                        if (!string.IsNullOrEmpty(sesionval))
                        {
                            Session.Remove("CreatePreviousURL");
                            return Redirect(sesionval);
                        }
                        else
                            return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.Clear();
                        return View();
                    }
                }

                return View(Obj_BusinessGallery);
            }
        }



        public ActionResult Edit(Int32? Businessgalleryid)
        {

            using (BusinessGalleryCtl db = new BusinessGalleryCtl())
            {
                BusinessGalleryClass obj_BusinessGallery = db.selectById(Businessgalleryid);
                Session["EditPreviousURL"] = Convert.ToString(ControllerContext.HttpContext.Request.UrlReferrer);
                return View(obj_BusinessGallery);
            }
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BusinessGalleryClass Obj_BusinessGallery)
        {
            using (BusinessGalleryCtl db = new BusinessGalleryCtl())
            {
                if (ModelState.IsValid)
                {
                    db.update(Obj_BusinessGallery);
                    string sesionval = Convert.ToString(Session["EditPreviousURL"]);
                    if (!string.IsNullOrEmpty(sesionval))
                    {
                        Session.Remove("EditPreviousURL");
                        return Redirect(sesionval);
                    }
                    else
                        return RedirectToAction("Index");
                }
                return View(Obj_BusinessGallery);
            }
        }



        public ActionResult Details(Int32? Businessgalleryid)
        {

            using (BusinessGalleryCtl db = new BusinessGalleryCtl())
            {
                BusinessGalleryClass obj_BusinessGallery = db.selectById(Businessgalleryid);
                return View(obj_BusinessGallery);
            }
        }



        public ActionResult Delete(Int32? Businessgalleryid)
        {
            using (BusinessGalleryCtl db = new BusinessGalleryCtl())
            {
                db.delete(Businessgalleryid);
                return RedirectToAction("Index");
            }
        }


        public ActionResult Index()
        {

            return View();
        }

        [HttpGet]
        public JsonResult SelectGalleryImages(Int32? Businessid)
        {
            using (BusinessGalleryCtl db = new BusinessGalleryCtl())
            {
                return Json(db.SelectGalleryImages(Businessid), JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult Index(string Businessid)
        {
            return View();
        }


        //[HttpPost]
        //public ActionResult UploadImages()
        //{
        //    Int32? BusinessId = 0;
        //    BusinessDirectoryClass obj_BusinessDirectory = new BusinessDirectoryClass();
        //    using (BusinessDirectoryCtl dbbdc = new BusinessDirectoryCtl())
        //    {
        //        try
        //        {
        //            for (int i = 0; i < Request.Form.Count; i++)
        //            {
        //                if (Request.Form.Keys[i] == "Businessid")
        //                {
        //                    BusinessId = Convert.ToInt32(Request.Form[i]);
        //                    if (BusinessId == 0)
        //                    {
        //                        Session.Remove("NewListingGallery");
        //                        List<BusinessGalleryClass> lstGallery = new List<BusinessGalleryClass>();
                                
        //                        for (int k = 0; k < Request.Form.Count; k++)
        //                        {
        //                            if (Request.Form.Keys[k] != "Businessid" && Request.Form.Keys[k] != "BusinessName")
        //                            {
        //                                if (!Directory.Exists(Server.MapPath("~/WebsiteImages/" + "BusinessGallery/" + Convert.ToString(Request.Form["BusinessName"]) + "/")))
        //                                {
        //                                    Directory.CreateDirectory(Server.MapPath("~/WebsiteImages/" + "BusinessGallery/" + Convert.ToString(Request.Form["BusinessName"]) + "/"));
        //                                }
        //                                string actFolder = Server.MapPath("~/WebsiteImages/" + "BusinessGallery/" + Convert.ToString(Request.Form["BusinessName"]) + "/");

        //                                if (Convert.ToString(Request.Form[k]).Contains("WebsiteImages/BusinessGallery"))
        //                                {

        //                                }
        //                                else
        //                                {
        //                                    byte[] imageBytes = Convert.FromBase64String(Request.Form[k].ToString().Replace("data:image/png;base64,", "").Replace("data:image/jpg;base64,", "").Replace("data:image/jpeg;base64,", "").Replace(" ", "+"));
        //                                    MemoryStream ms = new MemoryStream(imageBytes, 0, imageBytes.Length);
        //                                    ms.Write(imageBytes, 0, imageBytes.Length);
        //                                    System.Drawing.Image image2 = System.Drawing.Image.FromStream(ms, true);
        //                                    image2.Save(actFolder + Request.Form.Keys[k]);
        //                                }
        //                                BusinessGalleryClass bgc = new BusinessGalleryClass();
        //                                bgc.Businessid = BusinessId;
        //                                bgc.Imagename = Request.Form.Keys[k];
        //                                bgc.Sequence = i + 1;
        //                                lstGallery.Add(bgc);
        //                            }
        //                        }
        //                        Session["NewListingGallery"] = lstGallery;

        //                        return Json("Success", JsonRequestBehavior.AllowGet);
        //                    }
        //                    obj_BusinessDirectory = dbbdc.selectById(Convert.ToInt32(Request.Form[i]));
        //                }
        //            }
        //            using (BusinessGalleryCtl db = new BusinessGalleryCtl())
        //            {
        //                dt = db.selectByBusinessId(BusinessId);
        //                if (dt.Rows.Count > 0)
        //                {
        //                    for (int i = 0; i < dt.Rows.Count; i++)
        //                    {
        //                        string ImageName = Convert.ToString(dt.Rows[i]["ImageName"]);
        //                        Boolean HaveDelte = true;
        //                        for (int k= 0; k < Request.Form.Count; k++) {
        //                            if (ImageName.Trim() == Request.Form.Keys[k].Trim()) {
        //                                HaveDelte = false;
        //                            }
        //                        }

        //                        if (HaveDelte && System.IO.File.Exists(Server.MapPath("~/WebsiteImages/" + "BusinessGallery/" + obj_BusinessDirectory.Businessname + "/" + ImageName)))
        //                        {
        //                            System.IO.File.Delete(Server.MapPath("~/WebsiteImages/" + "BusinessGallery/" + obj_BusinessDirectory.Businessname + "/" + ImageName));
        //                        }
        //                    }
        //                    db.delete(BusinessId);
        //                }
        //                for (int i = 0; i < Request.Form.Count; i++)
        //                {
        //                    if (Request.Form.Keys[i] != "Businessid" && Request.Form.Keys[i] != "BusinessName")
        //                    {
        //                        if (!Directory.Exists(Server.MapPath("~/WebsiteImages/" + "BusinessGallery/" + obj_BusinessDirectory.Businessname + "/")))
        //                        {
        //                            Directory.CreateDirectory(Server.MapPath("~/WebsiteImages/" + "BusinessGallery/" + obj_BusinessDirectory.Businessname + "/"));
        //                        }
        //                        string actFolder = Server.MapPath("~/WebsiteImages/" + "BusinessGallery/" + obj_BusinessDirectory.Businessname + "/");

        //                        if (Convert.ToString(Request.Form[i]).Contains("WebsiteImages/BusinessGallery"))

ChossonKallahAdmin/Areas/Xpanel/Views/BusinessGallery/Create.cshtml
@model ChossonKallah.Models.BusinessGalleryClass









@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_MasterPage.cshtml";
}
<script src="~/Scripts/jquery1.8.3.min.js"></script>
<script src="~/Scripts/jquery-1.js"></script>
<script>

    $(document).ready(function () {
        $('div.header-nav').css('display', 'none');
    });

</script>@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="box-header" data-original-title>
        <h2><i class="halflings-icon white user"></i><span class="break"></span>Add Record</h2>
        <div class="box-icon">
        </div>
    </div>
    <div class="box-content">

        <div class="editor-field">
            @Html.HiddenFor(model => model.Businessgalleryid)
        </div>
        <div class="editor-label" style="font-weight:bold;">
            @Html.LabelFor(model => model.Businessid)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Businessid)
            @Html.ValidationMessageFor(model => model.Businessid)
        </div>
        <div class="editor-label" style="font-weight:bold;">
            @Html.LabelFor(model => model.Imagename)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Imagename)
            @Html.ValidationMessageFor(model => model.Imagename)
        </div>
        <div class="editor-label" style="font-weight:bold;">
            @Html.LabelFor(model => model.Isactive)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Isactive)
            @Html.ValidationMessageFor(model => model.Isactive)
        </div>
        <div class="editor-label" style="font-weight:bold;">
            @Html.LabelFor(model => model.Sequence)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Sequence)
            @Html.ValidationMessageFor(model => model.Sequence)
        </div>

        <div>
            <input type="submit" class="btn btn-primary" value="Save" />

            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn " })
        </div>

    </div>
}




<style>
    body {
        background-color: #EDEDED;
    }

    .fls {
        padding: 5px 20px;
    }

    .dfv {
        padding: 5px 20px;
    }
</style>

ChossonKallahAdmin/Areas/Xpanel/Views/BusinessGallery/Details.cshtml
 @model ChossonKallah.Models.BusinessGalleryClass 
 
  
 
 
 
  



 @{ 
			 ViewBag.Title = ""; 
 			  Layout =  "~/Views/Shared/_MasterPage.cshtml"; 
  } 
	 <script src="~/Scripts/jquery1.8.3.min.js"></script>
	 <script src="~/Scripts/jquery-1.js"></script>
	 <script>
		 
			 $(document).ready(function(){
				 $('div.header-nav').css('display','none');
			 });
		 
	 </script>
@{
		
		 <div class="box-header" data-original-title>
			 <h2><i class="halflings-icon white user"></i><span class="break"></span>View Record</h2>
			 <div class="box-icon">
			 </div>
		 </div>
		 <div class="box-content">
		  
		 <div class="editor-field">
			 @Html.HiddenFor(model => model.Businessgalleryid)
		 </div>
		 <div class="editor-label" style="font-weight:bold;" >
			 @Html.DisplayNameFor(model => model.Businessid)
		 </div>
		 <div class="editor-field">
			 @Html.DisplayFor(model => model.Businessid)
		 </div>
		 <div class="editor-label" style="font-weight:bold;" >
			 @Html.DisplayNameFor(model => model.Imagename)
		 </div>
		 <div class="editor-field">
			 @Html.DisplayFor(model => model.Imagename)
		 </div>
		 <div class="editor-label" style="font-weight:bold;" >
			 @Html.DisplayNameFor(model => model.Isactive)
		 </div>
		 <div class="editor-field">
			 @Html.DisplayFor(model => model.Isactive)
		 </div>
		 <div class="editor-label" style="font-weight:bold;" >
			 @Html.DisplayNameFor(model => model.Sequence)
		 </div>
		 <div class="editor-field">
			 @Html.DisplayFor(model => model.Sequence)
		 </div>
		 
		 
		 <div>@Html.ActionLink("Back to List", "Index",null,new{@class="btn"})</div>
		 
		 </div> 
}

  
 

 <style> body{ 
 background-color: #EDEDED; 
} 
 .fls{ 
 padding:5px 20px; 
} 
 .dfv{ 
 padding:5px 20px; 
} 
 </style>

ChossonKallahAdmin/Areas/Xpanel/Views/BusinessGallery/Edit.cshtml
 @model ChossonKallah.Models.BusinessGalleryClass 
 
  
 
 
 
  



 @{ 
			 ViewBag.Title = ""; 
 			  Layout =  "~/Views/Shared/_MasterPage.cshtml"; 
  } 
	 <script src="~/Scripts/jquery1.8.3.min.js"></script>
	 <script src="~/Scripts/jquery-1.js"></script>
	 <script>
		 
			 $(document).ready(function(){
				 $('div.header-nav').css('display','none');
			 });
		 
	 </script>@using (Html.BeginForm()) {
			 @Html.AntiForgeryToken()
			 @Html.ValidationSummary(true)
		 <div class="box-header" data-original-title>
			 <h2><i class="halflings-icon white user"></i><span class="break"></span>Edit Record</h2>
			 <div class="box-icon">
			 </div>
		 </div>
		 <div class="box-content">
		  
		 <div class="editor-field">
			 @Html.HiddenFor(model => model.Businessgalleryid)
		 </div>
		 <div class="editor-label" style="font-weight:bold;">
			 @Html.LabelFor(model => model.Businessid)
		 </div>
		 <div class="editor-field">
			 @Html.EditorFor(model => model.Businessid)
			 @Html.ValidationMessageFor(model => model.Businessid)
		 </div>
		 <div class="editor-label" style="font-weight:bold;">
			 @Html.LabelFor(model => model.Imagename)
		 </div>
		 <div class="editor-field">
			 @Html.EditorFor(model => model.Imagename)
			 @Html.ValidationMessageFor(model => model.Imagename)
		 </div>
		 <div class="editor-label" style="font-weight:bold;">
			 @Html.LabelFor(model => model.Isactive)
		 </div>
		 <div class="editor-field">
			 @Html.EditorFor(model => model.Isactive)
			 @Html.ValidationMessageFor(model => model.Isactive)
		 </div>
		 <div class="editor-label" style="font-weight:bold;">
			 @Html.LabelFor(model => model.Sequence)
		 </div>
		 <div class="editor-field">
			 @Html.EditorFor(model => model.Sequence)
			 @Html.ValidationMessageFor(model => model.Sequence)
		 </div>
		 
		 <div><input type="submit" value="Update" class="btn btn-primary" />
		 
		 @Html.ActionLink("Back to List", "Index",null,new{@class="btn"})</div>
		 
		 </div> 
}

  
 

 <style> body{ 
 background-color: #EDEDED; 
} 
 .fls{ 
 padding:5px 20px; 
} 
 .dfv{ 
 padding:5px 20px; 
} 
 </style>

ChossonKallahAdmin/Areas/Xpanel/Views/BusinessGallery/Index.cshtml
@model IEnumerable<ChossonKallah.Models.BusinessGalleryClass>
@using System.Web.Configuration
@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/HomeLayout.cshtml";
}
@{
    <style>
        ul.visualizacao.sortable.dropzone-previews.ui-sortable {
            border: none !important;
        }

        .dz-default.dz-message {
            padding: 50px 0px;
            margin-top: 15%;
            text-align: center;
            border: 1px solid #000;
        }

        .sortable {
            padding: 0;
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

            .sortable li {
                float: left;
                width: 120px;
                height: 150px;
                overflow: hidden;
                border: 1px solid red;
                text-align: center;
                margin: 5px;
            }

        li.sortable-placeholder {
            border: 1px dashed #CCC;
            background: none;
        }

        .dz-image-preview {
            position: relative;
        }

        .image-cancel img {
            color: red;
            font-size: 18px;
            position: absolute;
            top: 0;
            right: 0;
            font-weight: bold;
            margin-right: 10px;
            cursor: pointer;
            display: none;
            z-index: 100;
        }

        .dz-default.dz-message span {
            color: #000;
            font-size: 16px;
            font-weight: 600;
        }

        .dz-image-preview:hover .image-cancel img {
            background-color: #000;
            display: block;
        }

        a.dz-remove {
            color: red;
            padding: 5px 0px !important;
            display: inline-block;
        }
    </style>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.js"></script>
    using (Html.BeginForm("Index", "BusinessGallery", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div action="/Index" class="dropzone" drop-zone="" id="file-dropzone"></div>
        <ul class="visualizacao sortable dropzone-previews" style="border:1px solid #000"></ul>
        <div class="preview" style="display:none;">
            <li class="lilist" style="display:none;">
                <div>
                    <div class="dz-preview dz-file-preview dropzone dz-clickable" id="myDrop">
                        <img data-dz-thumbnail class="myimages" />
                        <div class="dz-progress"><span class="dz-upload" data-dz-uploadprogress></span></div>
                    </div>
                </div>
            </li>
        </div>
        <div class="col-md-12" style="text-align:center">
            <input type="button" onclick="UploadImages();" class="btn btn-primary" value="Upload" />
        </div>
    }
    <script>
        var Businessid = 0;
        $(document).ready(function () {
            $('.sortable').sortable();
            if (window.location.href.indexOf('Businessid') >= 0) {
                var splitdata = window.location.href.split('=');
                Businessid = splitdata[1];

            }
            bindPagingData(Businessid);
        });
        function bindPagingData(Businessid) {
            $.ajax({
                type: "Get",
                cache: false,
                url: "/BusinessGallery/SelectGalleryImages",
                data: { 'Businessid': Businessid },
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (response) {
                    debugger;
                    response = JSON.parse(response);
                    if (response.length > 0) {
                        $('.preview').attr('style', 'display:block');
                        $('.sortable').sortable('enable');
                    }
                    for (var i = 0; i < response.length; i++) {
                        var tbl = $('li.lilist:eq(0)').clone(true);

                        $(tbl).find('.myimages').attr('alt', response[i].ImageName)
                        $(tbl).find('.myimages').attr('src', "@WebConfigurationManager.AppSettings["BusinessGallery"]" + response[i].BusinessName + "/" + response[i].ImageName);
                        $('ul.visualizacao').append(tbl);

                    }
                    $('#success').hide();
                    $('#error').hide();
                },
                failure: function (response) {

                },
                error: function (response) {
                }
            });
        }
        function UploadImages() {
            var Businessid = 0;
            if (window.location.href.indexOf('Businessid') >= 0) {
                var splitdata = window.location.href.split('=');
                Businessid = splitdata[1];
            }
            alert(Businessid);
            var form = new FormData();
            for (var i = 0; i < $('.myimages').length; i++) {
                if ($('.myimages:eq(' + i + ')').attr('alt') != undefined && $('.myimages:eq(' + i + ')').attr('src') != undefined)
                    form.append($('.myimages:eq(' + i + ')').attr('alt'), $('.myimages:eq(' + i + ')').attr('src'));

            }
            form.append('Businessid', Businessid);
            $.ajax({
                type: "POST",
                cache: false,
                url: "/BusinessGallery/UploadImages",
                data: form,
                contentType: false,
                processData: false,
                success: function (response) {

                },
                failure: function (response) {

                },
                error: function (response) {
                }
            });
        }
        $.getScript('/Content/js/dropzone.min.js', function () {
            $('#file-dropzone').dropzone({
                url: "/BusinessGallery/Index",
                maxFilesize: 100,
                paramName: "uploadfile",
                maxThumbnailFilesize: 99999,
                previewsContainer: '.visualizacao',
                previewTemplate: $('.preview').html(),
                addRemoveLinks: true,
                init: function () {
                    this.on('completemultiple', function (file, json) {
                        $('.sortable').sortable('enable');
                    });
                    this.on('success', function (file, json) {
                    });
                    this.on('drop', function (file) {
                    });
                }
            });
        });
    </script>





}

ChossonKallahAdmin/Areas/Xpanel/Views/BusinessGallery/Indexpaging.cshtml
 @model IEnumerable<ChossonKallah.Models.BusinessGalleryClass> 
 
 



<script>
		 $(document).ready(function () {
			 var mydata = $('#RawDatas').parent('td').html();
			 $('#RawDatas').parent().parent().parent().parent('table').replaceWith(mydata);
		 
			 $("#AddressBookToggleAll").change(function () {
				 if ($(this).is(':checked')) {
					 $("input.k-checkbox[type=checkbox]").each(function () {
						 $(this).attr('checked', true);
					 }); 
				 } else {
					 $("input.k-checkbox[type=checkbox]").each(function () {
						  $(this).attr('checked', false);
					 });
				 }
			 }); 
		 }); 
 </script>
 


 
  


 
		 <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable" >
			 <tr>
				 <th>
				 </th>
				 <th >
					 @Html.DisplayNameFor(model => model.Businessid)
				 </th>
				 <th >
					 @Html.DisplayNameFor(model => model.Imagename)
				 </th>
				 <th >
					 @Html.DisplayNameFor(model => model.Isactive)
				 </th>
				 <th >
					 @Html.DisplayNameFor(model => model.Sequence)
				 </th>
				 <th>Action</th>
			 </tr>
		 @foreach (var item in Model) {
			 <tr>
				 <td>
					 @Html.HiddenFor(model => item.Businessgalleryid)
				 </td>
				 <td >
					 @Html.DisplayFor(model => item.Businessid)
				 </td>
				 <td >
					 @Html.DisplayFor(model => item.Imagename)
				 </td>
				 <td >
					 @Html.DisplayFor(model => item.Isactive)
				 </td>
				 <td >
					 @Html.DisplayFor(model => item.Sequence)
				 </td>
				 <td><a class="btn btn-info" style="padding:2px 7px; margin:2px;" href="/BusinessGallery/Edit?Businessgalleryid=@item.Businessgalleryid "><i class="halflings-icon white edit"></i></a>  
				 <a class="btn btn-success" style="padding:2px 7px; margin:2px;" href="/BusinessGallery/Details?Businessgalleryid=@item.Businessgalleryid "><i class="halflings-icon white zoom-in"></i></a>  
				 <a class="btn btn-danger" style="padding:2px 7px; margin:2px;" href="/BusinessGallery/Delete?Businessgalleryid=@item.Businessgalleryid" onclick="return confirm('Are you sure you want to delete this record.'); "><i class="halflings-icon white trash"></i></a> </td>
			 </tr>
		 }
		 </table>
		 
	 


 

   