ChossonKallahAdmin/Areas/Xpanel/Controllers/BusinessReviewController.cs
using ChossonKallah.Models;
using System;
using System.Net;
using System.Net.Sockets;
using System.Web.Mvc;
using ChossonKallahAdmin.GlobalUtilities;
using ChossonKallahAdmin.EF6;
using System.Data.SqlClient;
using System.Linq;

namespace ChossonKallahAdmin.Areas.Xpanel.Controllers
{
    public class BusinessReviewController : Controller
    {
        public ActionResult Create(Int32? Businessid)
        {
            BusinessReview bs = new BusinessReview();
            bs.BusinessID = Businessid;
            return View(bs);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BusinessReview Obj_BusinessReview, string command)
        {
            try
            {
                using (var context = new ChossonKallahAdmin.EF6.ChossonKallah())
                {
                    Obj_BusinessReview.AddedOn = System.DateTime.Now;
                    Obj_BusinessReview.IsDeleted = false;
                    context.BusinessReviews.Add(Obj_BusinessReview);
                    context.SaveChanges();
                    TempData["BusinessReviewSuccess"] = "Record has been added successfully.";
                    return RedirectToAction("Index", new { Businessid = Obj_BusinessReview.BusinessID });
                }
            }
            catch (Exception ex)
            {
                if (!ex.Message.Contains("See 'EntityValidationErrors' property"))
                    ViewBag.BusinessReviewError = ex.Message;
                return View(Obj_BusinessReview);
            }
            //using (BusinessReviewCtl db = new BusinessReviewCtl())
            //{

            //    db.insert(Obj_BusinessReview);
            //    return RedirectToAction("Index", new { Businessid = Obj_BusinessReview.Businessid });
            //}
        }

        public ActionResult Edit(Int32? Businessreviewid)
        {
            try
            {
                using (var context = new ChossonKallahAdmin.EF6.ChossonKallah())
                {
                    var BusinessreviewidPara = new SqlParameter("@Businessreviewid", Businessreviewid);
                    BusinessReview Obj_BusinessReview = context.Database.SqlQuery<BusinessReview>("sp_BusinessReview_select @Businessreviewid", BusinessreviewidPara).FirstOrDefault();
                    return View(Obj_BusinessReview);
                }
            }
            catch (Exception ex)
            {
                if (!ex.Message.Contains("See 'EntityValidationErrors' property"))
                    ViewBag.BusinessReviewError = ex.Message;
                return View();
            }
            //using (BusinessReviewCtl db = new BusinessReviewCtl())
            //{
            //    BusinessReviewClass obj_BusinessReview = db.selectById(Businessreviewid);
            //    return View(obj_BusinessReview);
            //}
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BusinessReview Obj_BusinessReview)
        {
            try
            {
                using (var context = new ChossonKallahAdmin.EF6.ChossonKallah())
                {
                    context.BusinessReviews.Attach(Obj_BusinessReview);
                    context.Entry(Obj_BusinessReview).State = System.Data.Entity.EntityState.Modified;
                    context.SaveChanges();
                    TempData["BusinessReviewSuccess"] = "Record has been update successfully.";
                    return RedirectToAction("Index", new { Businessid = Obj_BusinessReview.BusinessID });
                }
            }
            catch (Exception ex)
            {
                if (!ex.Message.Contains("See 'EntityValidationErrors' property"))
                    ViewBag.BusinessReviewError = ex.Message;
                return View(Obj_BusinessReview);
            }
            //using (BusinessReviewCtl db = new BusinessReviewCtl())
            //{
            //    db.update(Obj_BusinessReview);
            //    return RedirectToAction("Index", new { Businessid = Obj_BusinessReview.Businessid });
            //}
        }

        public ActionResult Delete(Int32? Businessreviewid)
        {
            try
            {
                using (var context = new ChossonKallahAdmin.EF6.ChossonKallah())
                {
                    var BusinessreviewidPara = new SqlParameter("@Businessreviewid", Businessreviewid);
                    BusinessReview obj_BusinessReview = context.Database.SqlQuery<BusinessReview>("sp_BusinessReview_select @Businessreviewid", BusinessreviewidPara).FirstOrDefault();
                    obj_BusinessReview.IsDeleted = true;
                    context.Entry(obj_BusinessReview).State = System.Data.Entity.EntityState.Modified;
                    context.SaveChanges();
                    TempData["BusinessReviewSuccess"] = "Record has been deleted successfully.";
                    return RedirectToAction("Index", new { Businessid = obj_BusinessReview.BusinessID });
                }
            }
            catch (Exception ex)
            {
                if (!ex.Message.Contains("See 'EntityValidationErrors' property"))
                    ViewBag.BusinessReviewError = ex.Message;
                return View();
            }
            //using (BusinessReviewCtl db = new BusinessReviewCtl())
            //{
            //    db.delete(Businessreviewid);
            //    return RedirectToAction("Index");
            //}
        }

        public ActionResult Index(Int32? Businessid)
        {
            try
            {
                using (var context = new ChossonKallahAdmin.EF6.ChossonKallah())
                {
                    var BusinessidPara = new SqlParameter("@Businessid", Businessid);
                    var obj_BusinessDirectory = context.Database.SqlQuery<BusinessDirectory>("sp_BusinessDirectory_select @Businessid", BusinessidPara).FirstOrDefault();
                    ViewBag.ListingName = obj_BusinessDirectory.BusinessName;
                    return View();
                }
            }
            catch (Exception ex)
            {
                if (!ex.Message.Contains("See 'EntityValidationErrors' property"))
                    ViewBag.BusinessReview = ex.Message;
                return View();

            }
            //string listingName = "";
            //using (BusinessDirectoryCtl dbLIsting = new BusinessDirectoryCtl())
            //{
            //    System.Data.DataTable dt = dbLIsting.selectdatatable(Businessid);
            //    if (dt.Rows.Count > 0)
            //    {
            //        listingName = Convert.ToString(dt.Rows[0]["BusinessName"]);
            //    }
            //}
            //ViewBag.ListingName = listingName;
            //return View();
        }

        [HttpGet]
        public ActionResult Indexpaging(Int64 PageSize, Int64 PageIndex, string Search, string Businessid)
        {
            try
            {
                using (var context = new ChossonKallahAdmin.EF6.ChossonKallah())
                {
                    var PageSizePara = new SqlParameter("@PageSize", PageSize);
                    var PageIndexPara = new SqlParameter("@PageIndex", PageIndex);
                    var SearchPara = new SqlParameter("@Search", Search);
                    var BusinessIdPara = new SqlParameter("@Businessid", Businessid);
                    var result = context.Database.SqlQuery<Listview>("sp_BusinessReview_selectIndexPaging @Businessid,@PageSize,@PageIndex,@Search", BusinessIdPara, PageSizePara, PageIndexPara, SearchPara).ToList();
                    return Json(SessionUtilities.ConvertDataTableTojSonString(SessionUtilities.LINQResultToDataTable(result)), JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(string.Format("Exception {0}", ex.Message), JsonRequestBehavior.AllowGet);
            }
            //using (BusinessReviewCtl db = new BusinessReviewCtl())
            //{
            //    return Json(db.selectIndexPaging(PageSize, PageIndex, Search, Businessid), JsonRequestBehavior.AllowGet);
            //}
        }
    }
}

ChossonKallahAdmin/Controllers/BusinessReviewController.cs
using ChossonKallah.Models;
using System;
using System.Net;
using System.Net.Sockets;
using System.Web.Mvc;
using ChossonKallahAdmin.GlobalUtilities;
using ChossonKallahAdmin.EF6;
using System.Data.SqlClient;
using System.Linq;

namespace ChossonKallah.Controllers
{
    public class BusinessReviewController : Controller
    {
        public ActionResult Create(Int32? Businessid)
        {
            BusinessReview bs = new BusinessReview();
            bs.BusinessID = Businessid;
            return View(bs);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BusinessReview Obj_BusinessReview, string command)
        {
            try
            {
                using (var context = new ChossonKallahAdmin.EF6.ChossonKallah())
                {
                    Obj_BusinessReview.AddedOn = System.DateTime.Now;
                    Obj_BusinessReview.IsDeleted = false;
                    context.BusinessReviews.Add(Obj_BusinessReview);
                    context.SaveChanges();
                    TempData["BusinessReviewSuccess"] = "Record has been added successfully.";
                    return RedirectToAction("Index", new { Businessid = Obj_BusinessReview.BusinessID });
                }
            }
            catch (Exception ex)
            {
                if (!ex.Message.Contains("See 'EntityValidationErrors' property"))
                    ViewBag.BusinessReviewError = ex.Message;
                return View(Obj_BusinessReview);
            }
            //using (BusinessReviewCtl db = new BusinessReviewCtl())
            //{

            //    db.insert(Obj_BusinessReview);
            //    return RedirectToAction("Index", new { Businessid = Obj_BusinessReview.Businessid });
            //}
        }

        public ActionResult Edit(Int32? Businessreviewid)
        {
            try
            {
                using (var context = new ChossonKallahAdmin.EF6.ChossonKallah())
                {
                    var BusinessreviewidPara = new SqlParameter("@Businessreviewid", Businessreviewid);
                    BusinessReview Obj_BusinessReview = context.Database.SqlQuery<BusinessReview>("sp_BusinessReview_select @Businessreviewid", BusinessreviewidPara).FirstOrDefault();
                    return View(Obj_BusinessReview);
                }
            }
            catch (Exception ex)
            {
                if (!ex.Message.Contains("See 'EntityValidationErrors' property"))
                    ViewBag.BusinessReviewError = ex.Message;
                return View();
            }
            //using (BusinessReviewCtl db = new BusinessReviewCtl())
            //{
            //    BusinessReviewClass obj_BusinessReview = db.selectById(Businessreviewid);
            //    return View(obj_BusinessReview);
            //}
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BusinessReview Obj_BusinessReview)
        {
            try
            {
                using (var context = new ChossonKallahAdmin.EF6.ChossonKallah())
                {
                    context.BusinessReviews.Attach(Obj_BusinessReview);
                    context.Entry(Obj_BusinessReview).State = System.Data.Entity.EntityState.Modified;
                    context.SaveChanges();
                    TempData["BusinessReviewSuccess"] = "Record has been update successfully.";
                    return RedirectToAction("Index", new { Businessid = Obj_BusinessReview.BusinessID });
                }
            }
            catch (Exception ex)
            {
                if (!ex.Message.Contains("See 'EntityValidationErrors' property"))
                    ViewBag.BusinessReviewError = ex.Message;
                return View(Obj_BusinessReview);
            }
            //using (BusinessReviewCtl db = new BusinessReviewCtl())
            //{
            //    db.update(Obj_BusinessReview);
            //    return RedirectToAction("Index", new { Businessid = Obj_BusinessReview.Businessid });
            //}
        }

        public ActionResult Delete(Int32? Businessreviewid)
        {
            try
            {
                using (var context = new ChossonKallahAdmin.EF6.ChossonKallah())
                {
                    var BusinessreviewidPara = new SqlParameter("@Businessreviewid", Businessreviewid);
                    BusinessReview obj_BusinessReview = context.Database.SqlQuery<BusinessReview>("sp_BusinessReview_select @Businessreviewid", BusinessreviewidPara).FirstOrDefault();
                    obj_BusinessReview.IsDeleted = true;
                    context.Entry(obj_BusinessReview).State = System.Data.Entity.EntityState.Modified;
                    context.SaveChanges();
                    TempData["BusinessReviewSuccess"] = "Record has been deleted successfully.";
                    return RedirectToAction("Index", new { Businessid = obj_BusinessReview.BusinessID });
                }
            }
            catch (Exception ex)
            {
                if (!ex.Message.Contains("See 'EntityValidationErrors' property"))
                    ViewBag.BusinessReviewError = ex.Message;
                return View();
            }
            //using (BusinessReviewCtl db = new BusinessReviewCtl())
            //{
            //    db.delete(Businessreviewid);
            //    return RedirectToAction("Index");
            //}
        }

        public ActionResult Index(Int32? Businessid)
        {
            try
            {
                using (var context = new ChossonKallahAdmin.EF6.ChossonKallah())
                {
                    var BusinessidPara = new SqlParameter("@Businessid", Businessid);
                    var obj_BusinessDirectory = context.Database.SqlQuery<BusinessDirectory>("sp_BusinessDirectory_select @Businessid", BusinessidPara).FirstOrDefault();
                    ViewBag.ListingName = obj_BusinessDirectory.BusinessName;
                    return View();
                }
            }
            catch (Exception ex)
            {
                if (!ex.Message.Contains("See 'EntityValidationErrors' property"))
                    ViewBag.BusinessReview = ex.Message;
                return View();

            }
            //string listingName = "";
            //using (BusinessDirectoryCtl dbLIsting = new BusinessDirectoryCtl())
            //{
            //    System.Data.DataTable dt = dbLIsting.selectdatatable(Businessid);
            //    if (dt.Rows.Count > 0)
            //    {
            //        listingName = Convert.ToString(dt.Rows[0]["BusinessName"]);
            //    }
            //}
            //ViewBag.ListingName = listingName;
            //return View();
        }

        [HttpGet]
        public ActionResult Indexpaging(Int64 PageSize, Int64 PageIndex, string Search, string Businessid)
        {
            try
            {
                using (var context = new ChossonKallahAdmin.EF6.ChossonKallah())
                {
                    var PageSizePara = new SqlParameter("@PageSize", PageSize);
                    var PageIndexPara = new SqlParameter("@PageIndex", PageIndex);
                    var SearchPara = new SqlParameter("@Search", Search);
                    var BusinessIdPara = new SqlParameter("@Businessid", Businessid);
                    var result = context.Database.SqlQuery<Listview>("sp_BusinessReview_selectIndexPaging @Businessid,@PageSize,@PageIndex,@Search", BusinessIdPara, PageSizePara, PageIndexPara, SearchPara).ToList();
                    return Json(SessionUtilities.ConvertDataTableTojSonString(SessionUtilities.LINQResultToDataTable(result)), JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(string.Format("Exception {0}", ex.Message), JsonRequestBehavior.AllowGet);
            }
            //using (BusinessReviewCtl db = new BusinessReviewCtl())
            //{
            //    return Json(db.selectIndexPaging(PageSize, PageIndex, Search, Businessid), JsonRequestBehavior.AllowGet);
            //}
        }
    }
}

ChossonKallahAdmin/Areas/Xpanel/Views/BusinessReview/Create.cshtml
@model ChossonKallahAdmin.EF6.BusinessReview
@{
    ViewBag.PageHead = "Add Review";
    Layout = "~/Areas/Xpanel/Views/Shared/HomeLayout.cshtml";
}
<script>
    $(document).ready(function () {
        var url = "https://api.ipify.org";
        $.ajax({
            url: url,
            success: function (results) {
                $('#AddedByIP').val(results);
            }
        });
        var Businessid = 0;
        if (window.location.href.indexOf('Businessid') >= 0) {
            var splitdata = window.location.href.split('=');
            Businessid = splitdata[1];
        }
        $('#Businessid').val(Businessid);
        $('div.header-nav').css('display', 'none');
    });
</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="alert alert-success" id="success" style="margin-top:20px;display:none">
        <strong>Success!</strong> <span class="successmessage"></span>
    </div>
    <div class="alert alert-danger" id="error" style="margin-top:20px;display:none">
        <strong>Error!</strong> <span class="errormessage"></span>
    </div>
    <br />
    <div class="panel panel-default">
        <div class="panel-heading">Add Review</div>
        <div class="panel-body">
            <div class="row clearfix">
                <div class="form-group">
                    @Html.HiddenFor(Model => Model.AddedByIP)
                    @Html.HiddenFor(model => model.BusinessReviewID)
                </div>
                <div class="clearfix">
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Review Name&nbsp; <label style="color:red;margin-bottom:0px;">*</label></label>
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @style = "color:red;margin-bottom:0px;font-size: 11px" })

                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Rating&nbsp; <label style="color:red;margin-bottom:0px;">*</label></label>
                        @Html.TextBoxFor(model => model.Rating, new { @class = "form-control", @maxlength = "1", @onkeypress = "return onlyNumber(event)" })
                    </div>
                </div>
                <div class="clearfix">
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Email&nbsp; <label style="color:red;margin-bottom:0px;">*</label></label>
                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @style = "color:red;margin-bottom:0px;font-size: 11px" })

                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Review&nbsp; <label style="color:red;margin-bottom:0px;">*</label></label>
                        @Html.TextBoxFor(model => model.Review, new { @class = "form-control" })
                    </div>
                </div>
                <div class="clearfix">
                </div>
                <div class="clearfix">
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Is Active</label>
                        @Html.EditorFor(model => model.isActive, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <input type="submit" onclick="return chckvalidation()" class="btn  btn-primary pull-left" style="margin-right:12px;" value="Save" />
                    @Html.ActionLink("Cancel", "Index", "BusinessReview", new { Businessid = Model.BusinessID }, new { @class = "btn  btn-primary pull-left", @style = "margin-right:12px;" })
                </div>
            </div>
        </div>
    </div>
}
<script src="~/Content/js/EmailValidation.js"></script>
<script>

    function chckvalidation() {
        debugger;
        var IsError = true;
        var errormessage = "";
        $('.errormessage').html('');
        if ($('#Name').val() == "") {
            $('.errormessage').html(errormessage + "<br/> - Review name is required.");
            errormessage = $('.errormessage').html();

            IsError = false;
            $('#error').show();
        }

        if ($('#Rating').val() == "") {
            $('.errormessage').html(errormessage + '<br/> - Rating is required.');
            errormessage = $('.errormessage').html();

            IsError = false;
            $('#error').show();
        }
        else {
            var rat = parseInt($('#Rating').val());
            if (rat > 0 && rat < 6) {

            }
            else {
                $('.errormessage').html(errormessage + '<br/> - Rating must be between 1 to 5.');
                errormessage = $('.errormessage').html();
                IsError = false;
                $('#error').show();
            }
        }

        if ($('#Email').val() == "") {
            $('.errormessage').html(errormessage + "<br/> - Email is required.");
            errormessage = $('.errormessage').html();

            IsError = false;
            $('#error').show();
        } else {

            if (IsEmail($('#Email').val())) {

            } else {
                $('.errormessage').html(errormessage + "<br/> - Enter valid email.");
                errormessage = $('.errormessage').html();
                IsError = false;
                $('#error').show();
            }
        }

        if ($('#Review').val() == "") {
            $('.errormessage').html(errormessage + "<br/> - Review is required.");
            errormessage = $('.errormessage').html();

            IsError = false;
            $('#error').show();
        }

        if (!IsError)
            $("html, body").animate({ scrollTop: 0 }, "slow");

        return IsError;
    }
</script>

<style>
    body {
        background-color: #EDEDED;
    }

    .fls {
        padding: 5px 20px;
    }

    .dfv {
        padding: 5px 20px;
    }
</style>

ChossonKallahAdmin/Areas/Xpanel/Views/BusinessReview/Edit.cshtml
@model ChossonKallahAdmin.EF6.BusinessReview
@{
    ViewBag.PageHead = "Edit Review";
    Layout = "~/Areas/Xpanel/Views/Shared/HomeLayout.cshtml";
}
<script>
    $(document).ready(function () {
        var url = "https://api.ipify.org";
        $.ajax({
            url: url,
            success: function (results) {
                $('#Addedbyip').val(results);
            }
        });
        var Businessid = 0;
        if (window.location.href.indexOf('Businessid') >= 0) {
            var splitdata = window.location.href.split('=');
            Businessid = splitdata[1];
        }
        $('#Businessid').val(Businessid);
        $('div.header-nav').css('display', 'none');
    });
</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="alert alert-success" id="success" style="margin-top:20px;display:none">
        <strong>Success!</strong> <span class="successmessage"></span>
    </div>
    <div class="alert alert-danger" id="error" style="margin-top:20px;display:none">
        <strong>Error!</strong> <span class="errormessage"></span>
    </div>
    <br />
    <div class="panel panel-default">
        <div class="panel-heading">Edit Review</div>
        <div class="panel-body">
            <div class="row clearfix">
                <div class="form-group">
                    @Html.HiddenFor(Model => Model.AddedByIP)
                    @Html.HiddenFor(model => model.BusinessReviewID)
                    @Html.HiddenFor(model => model.BusinessID)
                    @Html.HiddenFor(model => model.AddedOn)
                    @Html.HiddenFor(model => model.IsDeleted)
                </div>
                <div class="clearfix">
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Review Name&nbsp; <label style="color:red;margin-bottom:0px;">*</label></label>
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @style = "color:red;margin-bottom:0px;font-size: 11px" })
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Rating&nbsp; <label style="color:red;margin-bottom:0px;">*</label></label>
                        @Html.TextBoxFor(model => model.Rating, new { @class = "form-control", @maxlength = "1", @onkeypress = "return onlyNumber(event)" })
                    </div>
                </div>
                <div class="clearfix">
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Email&nbsp; <label style="color:red;margin-bottom:0px;">*</label></label>
                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @style = "color:red;margin-bottom:0px;font-size: 11px" })
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Review&nbsp; <label style="color:red;margin-bottom:0px;">*</label></label>
                        @Html.TextBoxFor(model => model.Review, new { @class = "form-control" })
                    </div>
                </div>
                <div class="clearfix">
                </div>
                <div class="clearfix">
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Is Active</label>
                        @Html.EditorFor(model => model.isActive, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <input type="submit" onclick="return chckvalidation()" class="btn  btn-primary pull-left" style="margin-right:12px;" value="Update" />
                    @Html.ActionLink("Cancel", "Index", "BusinessReview", new { Businessid = Model.BusinessID }, new { @class = "btn  btn-primary pull-left", @style = "margin-right:12px;" })
                </div>
            </div>
        </div>
    </div>
}
<script src="~/Content/js/EmailValidation.js"></script>
<script>

    function chckvalidation() {
        debugger;
        var IsError = true;
        var errormessage = "";
        $('.errormessage').html('');

        if ($('#Name').val() == "") {
            $('.errormessage').html(errormessage + "<br/> - Review name is required.");
            errormessage = $('.errormessage').html();
            IsError = false;
            $('#error').show();
        }

        if ($('#Rating').val() == "") {
            $('.errormessage').html(errormessage + '<br/> - Rating is required.');
            errormessage = $('.errormessage').html();
            IsError = false;
            $('#error').show();
        }
        else {
            var rat = parseInt($('#Rating').val());
            if (rat > 0 && rat < 6) {

            }
            else {
                $('.errormessage').html(errormessage + '<br/> - Rating must be between 1 to 5.');
                errormessage = $('.errormessage').html();
                IsError = false;
                $('#error').show();
            }
        }

        if ($('#Email').val() == "") {
            $('.errormessage').html(errormessage + "<br/> - Email is required.");
            errormessage = $('.errormessage').html();
            IsError = false;
            $('#error').show();
        }
        else {
            if (IsEmail($('#Email').val())) {
            } else {
                $('.errormessage').html(errormessage + "<br/> - Enter valid email.");
                errormessage = $('.errormessage').html();
                IsError = false;
                $('#error').show();
            }
        }

        if ($('#Review').val() == "") {
            $('.errormessage').html(errormessage + "<br/> - Review is required.");
            errormessage = $('.errormessage').html();
            IsError = false;
            $('#error').show();
        }

        if (!IsError)
            $("html, body").animate({ scrollTop: 0 }, "slow");
        return IsError;
    }
</script>

<style>
    body {
        background-color: #EDEDED;
    }

    .fls {
        padding: 5px 20px;
    }

    .dfv {
        padding: 5px 20px;
    }
</style>