ChossonKallahAdmin/Areas/Xpanel/Controllers/WebsiteBannerController.cs
using ChossonKallah.Models;
using System;
using System.IO;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using ChossonKallahAdmin.GlobalUtilities;
using ChossonKallahAdmin.EF6;
using System.Data.SqlClient;
using System.Linq;

namespace ChossonKallahAdmin.Areas.Xpanel.Controllers
{
    public class WebsiteBannerController : Controller
    {

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(WebsiteBanner Obj_WebsiteBanner, string command, HttpPostedFileBase BannerImage)
        {
            try
            {
                string BannerName = string.Empty;
                using (var context = new ChossonKallahAdmin.EF6.ChossonKallah())
                {
                    if (SessionUtilities.SaveImage(BannerImage, "Banner"))
                    {
                        BannerName = Path.GetFileName(BannerImage.FileName);
                        Obj_WebsiteBanner.BannerImage = BannerName;
                    }
                    Obj_WebsiteBanner.CreatedOn = System.DateTime.Now;
                    Obj_WebsiteBanner.IsDeleted = false;
                    context.WebsiteBanners.Add(Obj_WebsiteBanner);
                    context.SaveChanges();
                    var WebsitebannerSequenceidPara = new SqlParameter("@websitebannerid", Obj_WebsiteBanner.WebsiteBannerID);
                    context.Database.ExecuteSqlCommand("sp_WebsiteBanner_UpdateSequence @websitebannerid", WebsitebannerSequenceidPara);
                    TempData["WebsiteBannerSuccess"] = "Record has been added successfully.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                if (!ex.Message.Contains("See 'EntityValidationErrors' property"))
                    ViewBag.WebsiteBannerError = ex.Message;
                return View(Obj_WebsiteBanner);
            }
            //try
            //{
            //    string BannerName = string.Empty;
            //    using (WebsiteBannerCtl db = new WebsiteBannerCtl())
            //    {
            //        if (SessionUtilities.SaveImage(BannerImage, "Banner"))
            //        {
            //            BannerName = Path.GetFileName(BannerImage.FileName);
            //            Obj_WebsiteBanner.BannerImage = BannerName;
            //        }
            //        db.insert(Obj_WebsiteBanner);
            //        TempData["WebsiteBannerSuccess"] = "Record has been added successfully.";
            //    }
            //    return RedirectToAction("Index");

            //}
            //catch (Exception ex)
            //{
            //    return View(Obj_WebsiteBanner);
            //}
        }

        public ActionResult Edit(Int32? Websitebannerid)
        {
            try
            {
                using (var context = new ChossonKallahAdmin.EF6.ChossonKallah())
                {
                    var WebsitebanneridPara = new SqlParameter("@Websitebannerid", Websitebannerid);
                    WebsiteBanner obj_WebsiteBanner = context.Database.SqlQuery<WebsiteBanner>("sp_WebsiteBanner_select @Websitebannerid", WebsitebanneridPara).FirstOrDefault();
                    return View(obj_WebsiteBanner);
                }
            }
            catch (Exception ex)
            {
                if (!ex.Message.Contains("See 'EntityValidationErrors' property"))
                    ViewBag.WebsiteBannerError = ex.Message;
                return View(new Admin());
            }
            //using (WebsiteBannerCtl db = new WebsiteBannerCtl())
            //{
            //    WebsiteBannerClass obj_WebsiteBanner = db.selectById(Websitebannerid);
            //    return View(obj_WebsiteBanner);
            //}
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(WebsiteBanner Obj_WebsiteBanner, HttpPostedFileBase BannerImage)
        {
            try
            {
                string BannerName = string.Empty;
                using (var context = new ChossonKallahAdmin.EF6.ChossonKallah())
                {
                    var WebsitebanneridPara = new SqlParameter("@Websitebannerid", Obj_WebsiteBanner.WebsiteBannerID);
                    WebsiteBanner obj_WebsiteBannerResult = context.Database.SqlQuery<WebsiteBanner>("sp_WebsiteBanner_select @Websitebannerid", WebsitebanneridPara).FirstOrDefault();
                    if (SessionUtilities.SaveImage(BannerImage, "Banner"))
                    {
                        BannerName = Path.GetFileName(BannerImage.FileName);
                        Obj_WebsiteBanner.BannerImage = BannerName;
                    }
                    else
                    {
                        Obj_WebsiteBanner.BannerImage = obj_WebsiteBannerResult.BannerImage;
                    }
                    var WebsitebannerSequenceidPara = new SqlParameter("@Websitebannerid", Obj_WebsiteBanner.WebsiteBannerID);
                    var WebsitebannerSequencePara = new SqlParameter("@Sequence", Obj_WebsiteBanner.Sequence);
                    context.Database.ExecuteSqlCommand("sp_WebsiteBanner_updateSequenceEdit @Sequence,@Websitebannerid", WebsitebannerSequencePara,WebsitebannerSequenceidPara);
                    context.WebsiteBanners.Attach(Obj_WebsiteBanner);
                    context.Entry(Obj_WebsiteBanner).State = System.Data.Entity.EntityState.Modified;
                    context.SaveChanges();
                    TempData["WebsiteBannerSuccess"] = "Record has been update successfully.";
                    return RedirectToAction("Index");

                }
            }
            catch (Exception ex)
            {
                if (!ex.Message.Contains("See 'EntityValidationErrors' property"))
                    ViewBag.WebsiteBannerError = ex.Message;
                return View(Obj_WebsiteBanner);
            }
            //try
            //{
            //    string BannerName = string.Empty;
            //    using (WebsiteBannerCtl db = new WebsiteBannerCtl())
            //    {
            //        if (SessionUtilities.SaveImage(BannerImage, "Banner"))
            //        {
            //            BannerName = Path.GetFileName(BannerImage.FileName);
            //            Obj_WebsiteBanner.BannerImage = BannerName;
            //        }
            //        db.update(Obj_WebsiteBanner);
            //        TempData["WebsiteBannerSuccess"] = "Record has been updated successfully.";
            //    }
            //    return RedirectToAction("Index");
            //}
            //catch (Exception ex)
            //{
            //    return View(Obj_WebsiteBanner);
            //}
        }

        public ActionResult Delete(Int32? Websitebannerid)
        {
            try
            {
                using (var context = new ChossonKallahAdmin.EF6.ChossonKallah())
                {
                    var WebsitebanneridPara = new SqlParameter("@Websitebannerid", Websitebannerid);
                    WebsiteBanner obj_WebsiteBanner = context.Database.SqlQuery<WebsiteBanner>("sp_WebsiteBanner_select @Websitebannerid", WebsitebanneridPara).FirstOrDefault();
                    obj_WebsiteBanner.IsDeleted = true;
                    context.Entry(obj_WebsiteBanner).State = System.Data.Entity.EntityState.Modified;
                    context.SaveChanges();
                    var WebsitebannerSequenceidPara = new SqlParameter("@Websitebannerid", Websitebannerid);
                    context.Database.ExecuteSqlCommand("sp_WebsiteBanner_delete @Websitebannerid", WebsitebannerSequenceidPara);
                    TempData["WebsiteBannerSuccess"] = "Record has been deleted successfully.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                if (!ex.Message.Contains("See 'EntityValidationErrors' property"))
                    TempData["WebsiteBannerError"] = ex.Message;
                return RedirectToAction("Index");
            }
            //using (WebsiteBannerCtl db = new WebsiteBannerCtl())
            //{
            //    db.delete(Websitebannerid);
            //    TempData["WebsiteBannerSuccess"] = "Record has been deleted successfully.";
            //    return RedirectToAction("Index");
            //}
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult Indexpaging(Int64 PageSize, Int64 PageIndex, string Search)
        {
            try
            {
                using (var context = new ChossonKallahAdmin.EF6.ChossonKallah())
                {
                    var PageSizePara = new SqlParameter("@PageSize", PageSize);
                    var PageIndexPara = new SqlParameter("@PageIndex", PageIndex);
                    var SearchPara = new SqlParameter("@Search", Search);
                    var result = context.Database.SqlQuery<Listview>("sp_WebsiteBanner_selectIndexPaging @PageSize,@PageIndex,@Search", PageSizePara, PageIndexPara, SearchPara).ToList();
                    return Json(SessionUtilities.ConvertDataTableTojSonString(SessionUtilities.LINQResultToDataTable(result)), JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(string.Format("Exception {0}", ex.Message), JsonRequestBehavior.AllowGet);
            }
            //using (WebsiteBannerCtl db = new WebsiteBannerCtl())
            //{
            //    return Json(db.selectIndexPaging(PageSize, PageIndex, Search), JsonRequestBehavior.AllowGet);
            //}
        }
    }
}

ChossonKallahAdmin/Views/WebsiteBanner/Create.cshtml
@model ChossonKallahAdmin.EF6.WebsiteBanner
@{
    ViewBag.PageHead = "Add Banner";
    Layout = "~/Views/Shared/HomeLayout.cshtml";
}
<script>

    $(document).ready(function () {
        $('div.header-nav').css('display', 'none');
        //$("#Sequence").attr("disabled", "disabled");
    });

</script>
@using (Html.BeginForm("Create", "WebsiteBanner", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="alert alert-success" id="success" style="margin-top:20px;display:none">
        <strong>Success!</strong> <span class="successmessage"></span>
    </div>
    <div class="alert alert-danger" id="error" style="margin-top:20px;display:none">
        <strong>Error!</strong> <span class="errormessage"></span>
    </div>
    <br />
    <div class="panel panel-default">
        <div class="panel-heading">Add Banner</div>
        <div class="panel-body">
            <div class="row clearfix">
                <div class="form-group">
                    @Html.HiddenFor(model => model.WebsiteBannerID)
                </div>
                <div class="clearfix">
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Banner Name&nbsp; <label style="color:red;margin-bottom:0px;">*</label></label>
                        @Html.TextBoxFor(model => model.BannerName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.BannerName, "", new { @style = "color:red;margin-bottom:0px;font-size: 11px" })

                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Banner Image&nbsp; <label style="color:red;margin-bottom:0px;">*</label></label>
                        @Html.TextBoxFor(model => model.BannerImage, new { @class = "form-control", @type = "file" })
                        @Html.ValidationMessageFor(model => model.BannerImage, "", new { @style = "color:red;margin-bottom:0px;font-size: 11px" })

                    </div>
                </div>
                <div class="clearfix">
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Text Line 1&nbsp; <label style="color:red;margin-bottom:0px;">*</label></label>
                        @Html.TextBoxFor(model => model.BannerTextLine1, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.BannerTextLine1, "", new { @style = "color:red;margin-bottom:0px;font-size: 11px" })

                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Text Line 2&nbsp; <label style="color:red;margin-bottom:0px;">*</label></label>
                        @Html.TextBoxFor(model => model.BannerTextLine2, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.BannerTextLine2, "", new { @style = "color:red;margin-bottom:0px;font-size: 11px" })

                    </div>
                </div>
                <div class="clearfix">
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Is Active</label>
                        @Html.EditorFor(model => model.IsActive, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <input type="submit" onclick="return chckvalidation()" class="btn  btn-primary pull-left" style="margin-right:12px;" value="Save" />
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn  btn-primary pull-left", @style = "margin-right:12px;" })
                </div>
            </div>
        </div>
    </div>
}
<script>
    function chckvalidation() {
        $('#error1').hide();
        debugger;
        var IsError = true;
        var errormessage = "";
        $('.errormessage').html(errormessage);

        if ($('#BannerName').val() == "") {
            $('.errormessage').html(errormessage + '<br/> - Banner name is required.');
            errormessage = $('.errormessage').html();
            $("html, body").animate({ scrollTop: 0 }, "slow");
            IsError = false;
            $('#error').show();
        }
        if ($('#BannerImage').val() == "") {
            $('.errormessage').html(errormessage + '<br/> - Banner image is required.');
            errormessage = $('.errormessage').html();
            $("html, body").animate({ scrollTop: 0 }, "slow");
            IsError = false;
            $('#error').show();
        }
        if ($('#BannerTextLine1').val() == "") {
            $('.errormessage').html(errormessage + "<br/> - Banner text line 1 is required.");
            errormessage = $('.errormessage').html();
            $("html, body").animate({ scrollTop: 0 }, "slow");
            IsError = false;
            $('#error').show();
        }

        if ($('#BannerTextLine2').val() == "") {
            $('.errormessage').html(errormessage + "<br/> - Banner text line 2 is required.");
            errormessage = $('.errormessage').html();
            $("html, body").animate({ scrollTop: 0 }, "slow");
            IsError = false;
            $('#error').show();
        }
        return IsError;
    }
</script>

ChossonKallahAdmin/Views/WebsiteBanner/Details.cshtml
 @model ChossonKallah.Models.WebsiteBannerClass 
 
  
 
 
 
  



 @{ 
     ViewBag.Title = "";
     Layout = "~/Views/Shared/HomeLayout.cshtml";
  } 
	 <script src="~/Scripts/jquery1.8.3.min.js"></script>
	 <script src="~/Scripts/jquery-1.js"></script>
	 <script>
		 
			 $(document).ready(function(){
				 $('div.header-nav').css('display','none');
			 });
		 
	 </script>
@{

		 <div class="box-header" data-original-title>
			 <h2><i class="halflings-icon white user"></i><span class="break"></span>View Record</h2>
			 <div class="box-icon">
			 </div>
		 </div>
		 <div class="box-content">
		  
		 <div class="editor-field">
			 @Html.HiddenFor(model => model.Websitebannerid)
		 </div>
		 <div class="editor-label" style="font-weight:bold;" >
			 @Html.DisplayNameFor(model => model.Bannername)
		 </div>
		 <div class="editor-field">
			 @Html.DisplayFor(model => model.Bannername)
		 </div>
		 <div class="editor-label" style="font-weight:bold;" >
			 @Html.DisplayNameFor(model => model.Isactive)
		 </div>
		 <div class="editor-field">
			 @Html.DisplayFor(model => model.Isactive)
		 </div>
		 <div class="editor-label" style="font-weight:bold;" >
			 @Html.DisplayNameFor(model => model.Sequence)
		 </div>
		 <div class="editor-field">
			 @Html.DisplayFor(model => model.Sequence)
		 </div>
		 <div class="editor-label" style="font-weight:bold;" >
			 @Html.DisplayNameFor(model => model.Bannertextline1)
		 </div>
		 <div class="editor-field">
			 @Html.DisplayFor(model => model.Bannertextline1)
		 </div>
		 <div class="editor-label" style="font-weight:bold;" >
			 @Html.DisplayNameFor(model => model.Bannertextline2)
		 </div>
		 <div class="editor-field">
			 @Html.DisplayFor(model => model.Bannertextline2)
		 </div>
		 
		 
		 <div>@Html.ActionLink("Back to List", "Index",null,new{@class="btn"})</div>
		 
		 </div> 
}

  
 

 <style> body{ 
 background-color: #EDEDED; 
} 
 .fls{ 
 padding:5px 20px; 
} 
 .dfv{ 
 padding:5px 20px; 
} 
 </style>

ChossonKallahAdmin/Views/WebsiteBanner/Edit.cshtml
@model ChossonKallahAdmin.EF6.WebsiteBanner
@using System.Web.Configuration
@{
    ViewBag.PageHead = "Edit Banner";
    Layout = "~/Views/Shared/HomeLayout.cshtml";
}
<script>

    $(document).ready(function () {
        $('div.header-nav').css('display', 'none');
        if ('@Model.BannerImage'!= "")
            $("#imgBannerImage").attr('src', "@WebConfigurationManager.AppSettings["BusinessBannerURL"]" + '@Model.BannerImage');
        //else
        //    $("#BannerView").hide();
    });

</script>
@using (Html.BeginForm("Edit", "WebsiteBanner", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="alert alert-success" id="success" style="margin-top:20px;display:none">
        <strong>Success!</strong> <span class="successmessage"></span>
    </div>
    <div class="alert alert-danger" id="error" style="margin-top:20px;display:none">
        <strong>Error!</strong> <span class="errormessage"></span>
    </div>
    <br />
    <div class="panel panel-default">
        <div class="panel-heading">Edit Banner</div>
        <div class="panel-body">
            <div class="row clearfix">
                <div class="form-group">
                    @Html.HiddenFor(model => model.WebsiteBannerID)
                    @Html.HiddenFor(model => model.CreatedOn)
                    @Html.HiddenFor(model => model.DeletedOn)
                    @Html.HiddenFor(model => model.IsDeleted)
                </div>
                <div class="clearfix">
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Banner Name&nbsp; <label style="color:red;margin-bottom:0px;">*</label></label>
                        @Html.TextBoxFor(model => model.BannerName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.BannerName, "", new { @style = "color:red;margin-bottom:0px;font-size: 11px" })

                    </div>
                </div>
                <div class="clearfix">
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Banner Image</label>
                        @Html.TextBoxFor(model => model.BannerImage, new { @class = "form-control", @type = "file" })
                        @Html.ValidationMessageFor(model => model.BannerImage, "", new { @style = "color:red;margin-bottom:0px;font-size: 11px" })

                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <img id="imgBannerImage" height="80px;" />
                    </div>
                </div>
                <div class="clearfix">
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Text Line 1&nbsp; <label style="color:red;margin-bottom:0px;">*</label></label>
                        @Html.TextBoxFor(model => model.BannerTextLine1, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.BannerTextLine1, "", new { @style = "color:red;margin-bottom:0px;font-size: 11px" })

                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Text Line 2&nbsp; <label style="color:red;margin-bottom:0px;">*</label></label>
                        @Html.TextBoxFor(model => model.BannerTextLine2, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.BannerTextLine2, "", new { @style = "color:red;margin-bottom:0px;font-size: 11px" })

                    </div>
                </div>
                <div class="clearfix">
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Sequence</label>
                        @Html.TextBoxFor(model => model.Sequence, new { @class = "form-control", @onchange = "return GetMaxNumer()", @onkeypress = "return onlyNumber(event)" })
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 form-group ">
                        <label class="control-label">Is Active</label>
                        @Html.EditorFor(model => model.IsActive, new { @class = "form-control" })
                    </div>
                </div>
                <div class="clearfix">

                </div>

                <div class="form-group col-md-12">
                    <input type="submit" onclick="return chckvalidation()" class="btn  btn-primary pull-left" style="margin-right:12px;" value="Update" />
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn  btn-primary pull-left", @style = "margin-right:12px;" })
                </div>
            </div>
        </div>
    </div>
}
<script>
    function onlyNumber(e) {
        if (e.charCode == 48) {
            $('.errormessage').html('<br/> - 0 must not be allow in Sequence.');
            errormessage = $('.errormessage').html();
            $("html, body").animate({ scrollTop: 0 }, "slow");
            $('#error').show();
        }
        else {
            return (e.charCode > 47 && e.charCode < 58);
        }
    }
    function GetMaxNumer() {
        var lastrecod = '@Model.Sequence';
        var latestval = $('#Sequence').val();
        if ( latestval > lastrecod )
            $('#Sequence').val(lastrecod);
    }
    function chckvalidation() {
        $('#error1').hide();
        debugger;
        var IsError = true;
        var errormessage = "";
        $('.errormessage').html(errormessage);

        if ($('#Bannername').val() == "") {
            $('.errormessage').html(errormessage + '<br/> - Banner name is required.');
            errormessage = $('.errormessage').html();
            $("html, body").animate({ scrollTop: 0 }, "slow");
            IsError = false;
            $('#error').show();
        }

        if ($('#Bannertextline1').val() == "") {
            $('.errormessage').html(errormessage + "<br/> - Banner text line 1 is required.");
            errormessage = $('.errormessage').html();
            $("html, body").animate({ scrollTop: 0 }, "slow");
            IsError = false;
            $('#error').show();
        }
        if ($('#Bannertextline2').val() == "") {
            $('.errormessage').html(errormessage + "<br/> - Banner text line 2 is required.");
            errormessage = $('.errormessage').html();
            $("html, body").animate({ scrollTop: 0 }, "slow");
            IsError = false;
            $('#error').show();
        }
        if ($('#Sequence').val() == "") {
            $('.errormessage').html(errormessage + "<br/> - Sequence is required.");
            errormessage = $('.errormessage').html();
            $("html, body").animate({ scrollTop: 0 }, "slow");
            IsError = false;
            $('#error').show();
        }
        else {
            var seq = parseInt($('#Sequence').val());
            if (seq == 0) {
                $('.errormessage').html(errormessage + "<br/> - 0 must not be allow in Sequence.");
                errormessage = $('.errormessage').html();
                $("html, body").animate({ scrollTop: 0 }, "slow");
                IsError = false;
                $('#error').show();
            }
        }
        return IsError;
    }
</script>

ChossonKallahAdmin/Views/WebsiteBanner/Indexpaging.cshtml
 @model IEnumerable<ChossonKallah.Models.WebsiteBannerClass> 
 
 



<script>
		 $(document).ready(function () {
			 var mydata = $('#RawDatas').parent('td').html();
			 $('#RawDatas').parent().parent().parent().parent('table').replaceWith(mydata);
		 
			 $("#AddressBookToggleAll").change(function () {
				 if ($(this).is(':checked')) {
					 $("input.k-checkbox[type=checkbox]").each(function () {
						 $(this).attr('checked', true);
					 }); 
				 } else {
					 $("input.k-checkbox[type=checkbox]").each(function () {
						  $(this).attr('checked', false);
					 });
				 }
			 }); 
		 }); 
 </script>
 


 
  


 
		 <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable" >
			 <tr>
				 <th>
				 </th>
				 <th >
					 @Html.DisplayNameFor(model => model.Bannername)
				 </th>
				 <th >
					 @Html.DisplayNameFor(model => model.Isactive)
				 </th>
				 <th >
					 @Html.DisplayNameFor(model => model.Sequence)
				 </th>
				 <th >
					 @Html.DisplayNameFor(model => model.Bannertextline1)
				 </th>
				 <th >
					 @Html.DisplayNameFor(model => model.Bannertextline2)
				 </th>
				 <th>Action</th>
			 </tr>
		 @foreach (var item in Model) {
			 <tr>
				 <td>
					 @Html.HiddenFor(model => item.Websitebannerid)
				 </td>
				 <td >
					 @Html.DisplayFor(model => item.Bannername)
				 </td>
				 <td >
					 @Html.DisplayFor(model => item.Isactive)
				 </td>
				 <td >
					 @Html.DisplayFor(model => item.Sequence)
				 </td>
				 <td >
					 @Html.DisplayFor(model => item.Bannertextline1)
				 </td>
				 <td >
					 @Html.DisplayFor(model => item.Bannertextline2)
				 </td>
				 <td><a class="btn btn-info" style="padding:2px 7px; margin:2px;" href="/WebsiteBanner/Edit?Websitebannerid=@item.Websitebannerid "><i class="halflings-icon white edit"></i></a>  
				 <a class="btn btn-success" style="padding:2px 7px; margin:2px;" href="/WebsiteBanner/Details?Websitebannerid=@item.Websitebannerid "><i class="halflings-icon white zoom-in"></i></a>  
				 <a class="btn btn-danger" style="padding:2px 7px; margin:2px;" href="/WebsiteBanner/Delete?Websitebannerid=@item.Websitebannerid" onclick="return confirm('Are you sure you want to delete this record.'); "><i class="halflings-icon white trash"></i></a> </td>
			 </tr>
		 }
		 </table>
		 
	 


 

   