ChossonKallahAdmin/Areas/Xpanel/Controllers/GeneralSettingsController.cs
using ChossonKallah.Models;
using System;
using System.Web.Mvc;


namespace ChossonKallah.Controllers
{
    public class GeneralSettingsController : Controller
    {
        //private GeneralSettingsCtl db = new GeneralSettingsCtl();
        //{privateVariables}



        public ActionResult Create()
        {
            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                Session["CreatePreviousURL"] = Convert.ToString(ControllerContext.HttpContext.Request.UrlReferrer);
                return View();
            }

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GeneralSettingsClass Obj_GeneralSettings, string command)
        {

            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                if (ModelState.IsValid)
                {
                    db.insert(Obj_GeneralSettings);
                    if (command.ToLower().Trim() == "save")
                    {
                        string sesionval = Convert.ToString(Session["CreatePreviousURL"]);
                        if (!string.IsNullOrEmpty(sesionval))
                        {
                            Session.Remove("CreatePreviousURL");
                            return Redirect(sesionval);
                        }
                        else
                            return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.Clear();
                        return View();
                    }
                }

                return View(Obj_GeneralSettings);
            }
        }



        public ActionResult Edit(Int32? Generalsettings)
        {

            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                GeneralSettingsClass obj_GeneralSettings = db.selectById(Generalsettings);
                Session["EditPreviousURL"] = Convert.ToString(ControllerContext.HttpContext.Request.UrlReferrer);
                return View(obj_GeneralSettings);
            }
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(GeneralSettingsClass Obj_GeneralSettings)
        {
            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                if (ModelState.IsValid)
                {
                    db.update(Obj_GeneralSettings);
                    string sesionval = Convert.ToString(Session["EditPreviousURL"]);
                    if (!string.IsNullOrEmpty(sesionval))
                    {
                        Session.Remove("EditPreviousURL");
                        return Redirect(sesionval);
                    }
                    else
                        return RedirectToAction("Index");
                }
                return View(Obj_GeneralSettings);
            }
        }



        public ActionResult Details(Int32? Generalsettings)
        {

            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                GeneralSettingsClass obj_GeneralSettings = db.selectById(Generalsettings);
                return View(obj_GeneralSettings);
            }
        }



        public ActionResult Delete(Int32? Generalsettings)
        {
            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                db.delete(Generalsettings);
                return RedirectToAction("Index");
            }
        }


        public ActionResult Index()
        {

            return View();
        }



        public ActionResult Indexpaging(Int64 PageSize, Int64 PageIndex, string Search)
        {

            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                return PartialView(db.selectIndexPaging(PageSize, PageIndex, Search));
            }
        }
        public Int32 IndexpagingCount(Int64 PageSize, Int64 PageIndex, string Search)
        {

            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                return db.selectIndexPagingCount(PageSize, PageIndex, Search);
            }
        }

        public ActionResult IndexLazyLoading(Int64 StartIndex, Int64 EndIndex, string Search)
        {
            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                return PartialView(db.selectIndexLazyLoading(StartIndex, EndIndex, Search));
            }
        }


        public ActionResult VIndex()
        {

            return View();
        }



        public ActionResult VIndexpaging(Int64 PageSize, Int64 PageIndex, string Search)
        {

            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                return PartialView(db.selectIndexPaging(PageSize, PageIndex, Search));
            }
        }
        public Int32 VIndexpagingCount(Int64 PageSize, Int64 PageIndex, string Search)
        {

            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                return db.selectIndexPagingCount(PageSize, PageIndex, Search);
            }
        }

        public ActionResult VIndexLazyLoading(Int64 StartIndex, Int64 EndIndex, string Search)
        {
            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                return PartialView(db.selectIndexLazyLoading(StartIndex, EndIndex, Search));
            }
        }


        public ActionResult EditTableRowDelete(Int32? Generalsettings)
        {
            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                db.delete(Generalsettings);
                return RedirectToAction("EditTable");
            }
        }


        public ActionResult EditTable()
        {

            return View();
        }



        public ActionResult EditTablePaging(Int64 PageSize, Int64 PageIndex, string Search)
        {

            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                return PartialView(db.selectIndexPaging(PageSize, PageIndex, Search));
            }
        }
        public Int32 EditTablePagingCount(Int64 PageSize, Int64 PageIndex, string Search)
        {

            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                return db.selectIndexPagingCount(PageSize, PageIndex, Search);
            }
        }

        public ActionResult EditTableLazyLoading(Int64 StartIndex, Int64 EndIndex, string Search)
        {
            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                return PartialView(db.selectIndexLazyLoading(StartIndex, EndIndex, Search));
            }
        }

        [HttpPost]
        public ActionResult SaveRecords(FormCollection model)
        {
            if (ModelState.IsValid)
            {
                using (GeneralSettingsCtl db = new GeneralSettingsCtl())
                {
                    var GeneralsettingsArray = model.GetValues("item.Generalsettings");
                    var KeyArray = model.GetValues("item.Key");
                    var DescrpitionArray = model.GetValues("item.Descrpition");
                    for (Int32 i = 0; i < GeneralsettingsArray.Length; i++)
                    {
                        GeneralSettingsClass obj_update = db.selectById(Convert.ToInt32(GeneralsettingsArray[i]));
                        if (!string.IsNullOrEmpty(Convert.ToString(GeneralsettingsArray)))
                            obj_update.Generalsettings = Convert.ToInt32(GeneralsettingsArray[i]);
                        if (!string.IsNullOrEmpty(Convert.ToString(KeyArray)))
                            obj_update.Key = Convert.ToString(KeyArray[i]);
                        if (!string.IsNullOrEmpty(Convert.ToString(DescrpitionArray)))
                            obj_update.Descrpition = Convert.ToString(DescrpitionArray[i]);
                        db.update(obj_update);
                    }
                }
            }
            return RedirectToAction("EditTable");
        }

        public ActionResult EditTableRowsDelete(string records)
        {
            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                foreach (string id in records.Trim(',').Split(','))
                {
                    if (!string.IsNullOrEmpty(id.Trim()))
                    {
                        db.delete(Convert.ToInt32(id));
                    }
                }
                return View();
            }
        }
        //{ActionResultMethod}




    }

}

ChossonKallahAdmin/Controllers/GeneralSettingsController.cs
using ChossonKallah.Models;
using System;
using System.Web.Mvc;


namespace ChossonKallah.Controllers
{
    public class GeneralSettingsController : Controller
    {
        //private GeneralSettingsCtl db = new GeneralSettingsCtl();
        //{privateVariables}



        public ActionResult Create()
        {
            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                Session["CreatePreviousURL"] = Convert.ToString(ControllerContext.HttpContext.Request.UrlReferrer);
                return View();
            }

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GeneralSettingsClass Obj_GeneralSettings, string command)
        {

            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                if (ModelState.IsValid)
                {
                    db.insert(Obj_GeneralSettings);
                    if (command.ToLower().Trim() == "save")
                    {
                        string sesionval = Convert.ToString(Session["CreatePreviousURL"]);
                        if (!string.IsNullOrEmpty(sesionval))
                        {
                            Session.Remove("CreatePreviousURL");
                            return Redirect(sesionval);
                        }
                        else
                            return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.Clear();
                        return View();
                    }
                }

                return View(Obj_GeneralSettings);
            }
        }



        public ActionResult Edit(Int32? Generalsettings)
        {

            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                GeneralSettingsClass obj_GeneralSettings = db.selectById(Generalsettings);
                Session["EditPreviousURL"] = Convert.ToString(ControllerContext.HttpContext.Request.UrlReferrer);
                return View(obj_GeneralSettings);
            }
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(GeneralSettingsClass Obj_GeneralSettings)
        {
            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                if (ModelState.IsValid)
                {
                    db.update(Obj_GeneralSettings);
                    string sesionval = Convert.ToString(Session["EditPreviousURL"]);
                    if (!string.IsNullOrEmpty(sesionval))
                    {
                        Session.Remove("EditPreviousURL");
                        return Redirect(sesionval);
                    }
                    else
                        return RedirectToAction("Index");
                }
                return View(Obj_GeneralSettings);
            }
        }



        public ActionResult Details(Int32? Generalsettings)
        {

            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                GeneralSettingsClass obj_GeneralSettings = db.selectById(Generalsettings);
                return View(obj_GeneralSettings);
            }
        }



        public ActionResult Delete(Int32? Generalsettings)
        {
            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                db.delete(Generalsettings);
                return RedirectToAction("Index");
            }
        }


        public ActionResult Index()
        {

            return View();
        }



        public ActionResult Indexpaging(Int64 PageSize, Int64 PageIndex, string Search)
        {

            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                return PartialView(db.selectIndexPaging(PageSize, PageIndex, Search));
            }
        }
        public Int32 IndexpagingCount(Int64 PageSize, Int64 PageIndex, string Search)
        {

            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                return db.selectIndexPagingCount(PageSize, PageIndex, Search);
            }
        }

        public ActionResult IndexLazyLoading(Int64 StartIndex, Int64 EndIndex, string Search)
        {
            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                return PartialView(db.selectIndexLazyLoading(StartIndex, EndIndex, Search));
            }
        }


        public ActionResult VIndex()
        {

            return View();
        }



        public ActionResult VIndexpaging(Int64 PageSize, Int64 PageIndex, string Search)
        {

            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                return PartialView(db.selectIndexPaging(PageSize, PageIndex, Search));
            }
        }
        public Int32 VIndexpagingCount(Int64 PageSize, Int64 PageIndex, string Search)
        {

            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                return db.selectIndexPagingCount(PageSize, PageIndex, Search);
            }
        }

        public ActionResult VIndexLazyLoading(Int64 StartIndex, Int64 EndIndex, string Search)
        {
            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                return PartialView(db.selectIndexLazyLoading(StartIndex, EndIndex, Search));
            }
        }


        public ActionResult EditTableRowDelete(Int32? Generalsettings)
        {
            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                db.delete(Generalsettings);
                return RedirectToAction("EditTable");
            }
        }


        public ActionResult EditTable()
        {

            return View();
        }



        public ActionResult EditTablePaging(Int64 PageSize, Int64 PageIndex, string Search)
        {

            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                return PartialView(db.selectIndexPaging(PageSize, PageIndex, Search));
            }
        }
        public Int32 EditTablePagingCount(Int64 PageSize, Int64 PageIndex, string Search)
        {

            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                return db.selectIndexPagingCount(PageSize, PageIndex, Search);
            }
        }

        public ActionResult EditTableLazyLoading(Int64 StartIndex, Int64 EndIndex, string Search)
        {
            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                return PartialView(db.selectIndexLazyLoading(StartIndex, EndIndex, Search));
            }
        }

        [HttpPost]
        public ActionResult SaveRecords(FormCollection model)
        {
            if (ModelState.IsValid)
            {
                using (GeneralSettingsCtl db = new GeneralSettingsCtl())
                {
                    var GeneralsettingsArray = model.GetValues("item.Generalsettings");
                    var KeyArray = model.GetValues("item.Key");
                    var DescrpitionArray = model.GetValues("item.Descrpition");
                    for (Int32 i = 0; i < GeneralsettingsArray.Length; i++)
                    {
                        GeneralSettingsClass obj_update = db.selectById(Convert.ToInt32(GeneralsettingsArray[i]));
                        if (!string.IsNullOrEmpty(Convert.ToString(GeneralsettingsArray)))
                            obj_update.Generalsettings = Convert.ToInt32(GeneralsettingsArray[i]);
                        if (!string.IsNullOrEmpty(Convert.ToString(KeyArray)))
                            obj_update.Key = Convert.ToString(KeyArray[i]);
                        if (!string.IsNullOrEmpty(Convert.ToString(DescrpitionArray)))
                            obj_update.Descrpition = Convert.ToString(DescrpitionArray[i]);
                        db.update(obj_update);
                    }
                }
            }
            return RedirectToAction("EditTable");
        }

        public ActionResult EditTableRowsDelete(string records)
        {
            using (GeneralSettingsCtl db = new GeneralSettingsCtl())
            {
                foreach (string id in records.Trim(',').Split(','))
                {
                    if (!string.IsNullOrEmpty(id.Trim()))
                    {
                        db.delete(Convert.ToInt32(id));
                    }
                }
                return View();
            }
        }
        //{ActionResultMethod}




    }

}

ChossonKallahAdmin/Areas/Xpanel/Views/GeneralSettings/Create.cshtml
 @model ChossonKallah.Models.GeneralSettingsClass 
 
  
 
 
 
  



 @{ 
     ViewBag.Title = "";
     Layout = "~/Views/Shared/HomeLayout.cshtml";
  } 
	 <script src="~/Scripts/jquery1.8.3.min.js"></script>
	 <script src="~/Scripts/jquery-1.js"></script>
	 <script>
		 
			 $(document).ready(function(){
				 $('div.header-nav').css('display','none');
			 });
		 
	 </script>@using (Html.BeginForm()) {
		 @Html.AntiForgeryToken()
		 @Html.ValidationSummary(true)
		 <div class="box-header" data-original-title>
			 <h2><i class="halflings-icon white user"></i><span class="break"></span>Add Record</h2>
			 <div class="box-icon">
			 </div>
		 </div>
		 <div class="box-content">
		  
		 <div class="editor-field">
			 @Html.HiddenFor(model => model.Generalsettings)
		 </div>
		 <div class="editor-label" style="font-weight:bold;">
			 @Html.LabelFor(model => model.Key)
		 </div>
		 <div class="editor-field">
			 @Html.EditorFor(model => model.Key)
			 @Html.ValidationMessageFor(model => model.Key)
		 </div>
		 <div class="editor-label" style="font-weight:bold;">
			 @Html.LabelFor(model => model.Descrpition)
		 </div>
		 <div class="editor-field">
			 @Html.EditorFor(model => model.Descrpition)
			 @Html.ValidationMessageFor(model => model.Descrpition)
		 </div>
		 
		 <div><input type="submit" class="btn btn-primary" value="Save" />
		 
		 @Html.ActionLink("Back to List", "Index",null,new{@class="btn "})</div> 
		 
		 </div> 
}

  
 

 <style> body{ 
 background-color: #EDEDED; 
} 
 .fls{ 
 padding:5px 20px; 
} 
 .dfv{ 
 padding:5px 20px; 
} 
 </style>

ChossonKallahAdmin/Areas/Xpanel/Views/GeneralSettings/Details.cshtml
 @model ChossonKallah.Models.GeneralSettingsClass 
 
  
 
 
 
  



 @{ 
			 ViewBag.Title = ""; 
 			  Layout =  "~/Views/Shared/_MasterPage.cshtml"; 
  } 
	 <script src="~/Scripts/jquery1.8.3.min.js"></script>
	 <script src="~/Scripts/jquery-1.js"></script>
	 <script>
		 
			 $(document).ready(function(){
				 $('div.header-nav').css('display','none');
			 });
		 
	 </script>
@{
		
		 <div class="box-header" data-original-title>
			 <h2><i class="halflings-icon white user"></i><span class="break"></span>View Record</h2>
			 <div class="box-icon">
			 </div>
		 </div>
		 <div class="box-content">
		  
		 <div class="editor-field">
			 @Html.HiddenFor(model => model.Generalsettings)
		 </div>
		 <div class="editor-label" style="font-weight:bold;" >
			 @Html.DisplayNameFor(model => model.Key)
		 </div>
		 <div class="editor-field">
			 @Html.DisplayFor(model => model.Key)
		 </div>
		 <div class="editor-label" style="font-weight:bold;" >
			 @Html.DisplayNameFor(model => model.Descrpition)
		 </div>
		 <div class="editor-field">
			 @Html.DisplayFor(model => model.Descrpition)
		 </div>
		 
		 
		 <div>@Html.ActionLink("Back to List", "Index",null,new{@class="btn"})</div>
		 
		 </div> 
}

  
 

 <style> body{ 
 background-color: #EDEDED; 
} 
 .fls{ 
 padding:5px 20px; 
} 
 .dfv{ 
 padding:5px 20px; 
} 
 </style>

ChossonKallahAdmin/Areas/Xpanel/Views/GeneralSettings/Index.cshtml
@model IEnumerable<ChossonKallah.Models.GeneralSettingsClass>
@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/HomeLayout.cshtml";
}

<script>
		  $(document).ready(function () {
			 $('#lblPageIndex').html(1);
			 window.onload = function () { document.getElementById("loading").style.display = "block"; }
			  $('#RawDatas').addClass('loading');
			 var url = '@Url.Action("Indexpaging", "GeneralSettings")';
			 var urlCount = '@Url.Action("IndexpagingCount", "GeneralSettings")';
			 $('#RawDatas').load(url, { PageSize: $('#PageSize').val(), PageIndex: 1, Search: '' }, function () {
				 $('#RawDatas').removeClass('loading');
			 });
			 $('#TotalPageRecord').load(urlCount, { PageSize: $('#PageSize').val(), PageIndex: -1, Search: '' }, function (data) {
				 $(this).val(data);
				 $('li.prev').hide();
				 var totalRecs = $(this).val();
				 var selectedPageSize = parseInt($('#PageSize').val());
				 if (parseInt(totalRecs) <= selectedPageSize) {
					 $('li.next').hide();
				 }
			 });
			 $('#PageSize').on('change', function () {
				  $('#RawDatas').addClass('loading');
				 $('div.dataTables_paginate').hide();
				 $('#CurrentPageIndex').val(1);
				 var selectedPageSize = $(this).val();
				 $('#RawDatas').load(url, { PageSize: selectedPageSize, PageIndex: 1, Search: '' }, function () {
					 $('#RawDatas').removeClass('loading');
					  $('div.dataTables_paginate').css('display', 'block');
					 $('div.dataTables_paginate').show();
				 });
				 $('#TotalPageRecord').load(urlCount, { PageSize: selectedPageSize, PageIndex: -1, Search: '' }, function (data) {
					 $(this).val(data);
					 $('li.prev').hide();
					 var totalRecs = $(this).val();
					 if (parseInt(1) < (parseInt(totalRecs) / parseInt(selectedPageSize))) {
						  $('li.next').show();
					 } else {
						  $('li.next').hide();
					 }
				 });
				 $('#lblPageIndex').html(1);
			  });
				  $('li.next').click(function () {
					 $('#RawDatas').addClass('loading');
					 $('div.dataTables_paginate').hide();
					 var selectedPageSize = $('#PageSize').val();
					 var currentPageIndexval = parseInt($('#CurrentPageIndex').val()) + 1;
					 $('#RawDatas').html('');
					 $('#RawDatas').load(url, { PageSize: selectedPageSize, PageIndex: currentPageIndexval, Search: '' }, function () {
						 $('#RawDatas').removeClass('loading');
						 $('#CurrentPageIndex').val(currentPageIndexval);
						 $('div.dataTables_paginate').css('display', 'block');
						 $('div.dataTables_paginate').show();
					 });
					 $('#TotalPageRecord').load(urlCount, { PageSize: selectedPageSize, PageIndex: -1, Search: '' }, function (data) {
					 $(this).val(data);
					 $('li.prev').show();
					 var totalRecs = $(this).val();
					 if (parseInt(currentPageIndexval) < (parseInt(totalRecs) / parseInt(selectedPageSize))) {
						 $('li.next').show();
					 } else {
						  $('li.next').hide();
					 }
				 });
				  $('#lblPageIndex').html(currentPageIndexval);
			 });
			 $('li.prev').click(function () {
				  $('#RawDatas').addClass('loading');
				 $('div.dataTables_paginate').hide();
				 var selectedPageSize = $('#PageSize').val();
				 var currentPageIndexval = parseInt($('#CurrentPageIndex').val()) - 1;
				 $('#RawDatas').html('');
				  $('#RawDatas').load(url, { PageSize: selectedPageSize, PageIndex: currentPageIndexval, Search: '' }, function () {
					 $('#RawDatas').removeClass('loading');
					 $('#CurrentPageIndex').val(currentPageIndexval);
					 $('div.dataTables_paginate').css('display', 'block');
					 $('div.dataTables_paginate').show();
				 });
				 $('#TotalPageRecord').load(urlCount, { PageSize: selectedPageSize, PageIndex: -1, Search: '' }, function (data) {
					 $(this).val(data);
					 var totalRecs = $(this).val();
					 if (parseInt(currentPageIndexval) < (parseInt(totalRecs) / parseInt(selectedPageSize))) {
						  $('li.next').show();
					 } else {
						 $('li.next').hide();
					 }
					 if (parseInt(currentPageIndexval) > 1) {
						 $('li.prev').show();
					} else {
						 $('li.prev').hide();
					 }
				 });
				 $('#lblPageIndex').html(currentPageIndexval);
			 });
		 });

			 $(document).ready(function(){
				 $('div.header-nav').css('display','none');
			 });

</script>

@{

    <div class="box-header" data-original-title>
        <h2><i class="halflings-icon white user"></i><span class="break"></span>Show Table</h2>
        <div class="box-icon">
        </div>
    </div>
    <div class="box-content">

        <p>@Html.ActionLink("Add", "Create", null, new { @class = "btn btn-primary" }) </p>
        <div id="RawDatas">	   </div>

        <div class="pagination">
            <ul style="padding-left:10px; float:left; margin:0px 0px 20px">
                <li class="prev">
                    <a href="#">Previous</a>
                </li>
                <li class="active">
                    <a href="#">
                        <label id="lblPageIndex" style="margin:0px;"></label>
                    </a>
                </li>
                <li class="next">
                    <a href="#">Next</a>
                </li>
            </ul>
            <input type="hidden" id="CurrentPageIndex" value='1' />
            <input type="hidden" id="TotalPageRecord" value='0' />
            <input type="hidden" id="StartIndex" value="1" />
            <input type="hidden" id="EndIndex" value="10" />
            <div style=" float: right; line-height: 13px; padding: 1px 10px 1px 5px;">
                <select id="PageSize">
                    <option selected="selected" value="10">10</option>
                    <option value="20">20</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                </select>
                <span style="line-height: 25px; vertical-align: bottom;">Records/Page</span>
            </div>
            <input type="hidden" id="scrollIndex" value="0" />
        </div>

    </div>
}




<style>

    body {
        background-color: #EDEDED;
    }

    .fls {
        padding: 5px 20px;
    }

    .dfv {
        padding: 5px 20px;
    }

    .loading {
        color: white;
        padding: 5px 10px;
        text-align: center;
        font-size: 20px;
        font-weight: bold;
        width: 98%;
        display: block;
        min-height: 200px;
        background: url('../../Content/img/loading-img.gif') no-repeat center center;
        z-index: 999999999;
    }

        .loading table {
            opacity: 0;
        }

    .pagination {
        margin: 20px 0;
    }

        .pagination ul {
            display: inline-block;
            *display: inline;
            margin-bottom: 0;
            margin-left: 0;
            -webkit-border-radius: 4px;
            -moz-border-radius: 4px;
            border-radius: 4px;
            *zoom: 1;
            -webkit-box-shadow: 0 1px 2px rgba(0,0,0,0.05);
            -moz-box-shadow: 0 1px 2px rgba(0,0,0,0.05);
            box-shadow: 0 1px 2px rgba(0,0,0,0.05);
        }

            .pagination ul > li {
                display: inline;
            }

                .pagination ul > li > a, .pagination ul > li > span {
                    float: left;
                    padding: 4px 12px;
                    line-height: 20px;
                    text-decoration: none;
                    background-color: #fff;
                    border: 1px solid #ddd;
                }

                    .pagination ul > li > a:hover, .pagination ul > li > a:focus, .pagination ul > .active > a, .pagination ul > .active > span {
                        background-color: #f5f5f5;
                    }

            .pagination ul > .active > a, .pagination ul > .active > span {
                color: #999;
                cursor: default;
            }

            .pagination ul li a {
                color: #999;
            }

            .pagination ul > .disabled > span, .pagination ul > .disabled > a, .pagination ul > .disabled > a:hover, .pagination ul > .disabled > a:focus {
                color: #999;
                cursor: default;
                background-color: transparent;
            }

            .pagination ul > li:first-child > a, .pagination ul > li:first-child > span {
                border-left-width: 1px;
                -webkit-border-bottom-left-radius: 4px;
                border-bottom-left-radius: 4px;
                -webkit-border-top-left-radius: 4px;
                border-top-left-radius: 4px;
                -moz-border-radius-bottomleft: 4px;
                -moz-border-radius-topleft: 4px;
            }

            .pagination ul > li:last-child > a, .pagination ul > li:last-child > span {
                -webkit-border-top-right-radius: 4px;
                border-top-right-radius: 4px;
                -webkit-border-bottom-right-radius: 4px;
                border-bottom-right-radius: 4px;
                -moz-border-radius-topright: 4px;
                -moz-border-radius-bottomright: 4px;
            }
</style>